export default [
   {
    "login": "supriti10",
  "id": 146414328,
  "node_id": "U_kgDOCLoa-A",
  "avatar_url": "https://avatars.githubusercontent.com/u/146414328?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/supriti10",
  "html_url": "https://github.com/supriti10",
  "followers_url": "https://api.github.com/users/supriti10/followers",
  "following_url": "https://api.github.com/users/supriti10/following{/other_user}",
  "gists_url": "https://api.github.com/users/supriti10/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/supriti10/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/supriti10/subscriptions",
  "organizations_url": "https://api.github.com/users/supriti10/orgs",
  "repos_url": "https://api.github.com/users/supriti10/repos",
  "events_url": "https://api.github.com/users/supriti10/events{/privacy}",
  "received_events_url": "https://api.github.com/users/supriti10/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 2,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2023-09-29T05:51:37Z",
  "updated_at": "2024-06-05T09:19:50Z"
   },
]